# Generated by Django 5.0.2 on 2024-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0002_workplace_studentprofile_alumniprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_profile/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile/'),
        ),
    ]
