# Generated by Django 5.0.2 on 2024-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0003_remove_alumniprofile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/alumniPF/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/studentPF/'),
        ),
    ]
