# Generated by Django 5.0.2 on 2024-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0004_alter_alumniprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
