# Generated by Django 5.0.2 on 2024-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0005_workplace_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='graduated_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='started_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduated_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='started_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
