# Generated by Django 5.0.2 on 2024-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0006_alter_alumniprofile_graduated_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
