# Generated by Django 5.0.2 on 2024-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show_contact_info',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
