# Generated by Django 5.0.2 on 2024-04-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0013_alter_userprofile_show_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MIS_Alumni_App.workplace'),
        ),
        migrations.AddField(
            model_name='currentstudentprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currentstudentprofile',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MIS_Alumni_App.workplace'),
        ),
    ]
