# Generated by Django 5.0.2 on 2024-04-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_Alumni_App', '0015_remove_event_description_event_organizer_event_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='previous_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='previous_workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='former_employee', to='MIS_Alumni_App.workplace'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_employee', to='MIS_Alumni_App.workplace'),
        ),
    ]
